"use client"

import React, { useCallback, useEffect, useState } from "react"
import ReactMarkdown from "react-markdown"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./ui/card"
import { Input } from "./ui/input"
import { Button } from "./ui/button"
import Link from "next/link"
import { AIPresetSelector } from "@/components/ai-preset-selector"
import { makeAIRequest } from "@/lib/utils/ai-request"
import { useAiPresets, type AIPreset } from "@/lib/hooks/use-ai-presets"

type AppTimeData = {
  appName: string
  time: number
  fill: string
}

type DailyScreenTime = {
  date: string // Date in YYYY-MM-DD format
  totalTime: number // Total screen time in milliseconds
  appDistribution: Record<string, { time: number; fill: string }> // Time spent per app in milliseconds with color
}

type Props = {
  appTimeData: AppTimeData[]
  dailyScreenTimeData: DailyScreenTime[]
}

const systemPrompt = `
You are an AI assistant specialized in productivity analysis.
Your task is to analyze the user's screen time and app usage data, provide a detailed summary of their usage patterns, and offer actionable suggestions for improving productivity and reducing unnecessary screen time. 
Your response should include:
**Usage Summary:** Breakdown of total screen time and app usage distribution.
**Trends & Patterns:** Identify usage trends over days and highlight frequent and excessive usage.
**Productivity Assessment:** Evaluate whether the time spent on certain applications is productive or unproductive.
**Recommendations:** Provide practical strategies for optimizing screen time, reducing distractions, and increasing efficiency.
**Actionable Insights:** Specific goals or habits the user can implement to enhance productivity.

Ensure that your response is personalized, clear, and constructive.
`

const userPrompt = `
I have collected data on how I spend my time on different apps and my overall screen time per day. I want you to analyze this data and provide insights on:

- How much time I spend on each application.
- The overall trend of my screen time.
- Whether my screen time is excessive and how I can reduce it.
- Which apps are contributing the most to my usage.
- How I can improve my productivity by optimizing my time spent on apps.
- Any unhealthy usage patterns you notice.
- Suggestions for maintaining a healthier work-life balance.

IMPORTANT - The time is in milliseconds
IMPORTANT - Return the output in a html format wrapped in a div, dont add any backticks or stuff just return the plain string with html type code in it. Also bold titles and add proper linebreaks after each section (section includes the title and content) for readability.
`

const Summary = ({ appTimeData, dailyScreenTimeData }: Props) => {
  const [summary, setSummary] = useState<string>("")
  const [loading, setLoading] = useState<boolean>(false)
  const { getPreset } = useAiPresets()

  const dataPrompt = `
**Here is my data:**
**Total App Usage Data:**
${JSON.stringify(appTimeData, null, 2)}

**Screen Time Per Day with App Distribution:**
${JSON.stringify(dailyScreenTimeData, null, 2)}

Please provide a structured and detailed analysis along with practical recommendations to improve my digital habits.
`

  const fetchSummary = useCallback(async () => {
    const preset = getPreset()
    if (!preset) {
      setSummary("Please select an AI preset to generate summary")
      return
    }
    
    try {
      setLoading(true)
      
      const messages = [
        {
          role: "system" as const,
          content: systemPrompt,
        },
        {
          role: "user" as const,
          content: userPrompt + "\n" + dataPrompt,
        },
      ]

      const result = await makeAIRequest({ messages, preset })
      setSummary(result)
    } catch (error) {
      setSummary(
        error instanceof Error
          ? error.message
          : "Something went wrong while fetching data from AI"
      )
    } finally {
      setLoading(false)
    }
  }, [getPreset, dataPrompt])

  const canGenerateSummary = useCallback(() => {
    const preset = getPreset()
    return !!preset
  }, [getPreset])

  const handlePresetSelect = (preset: AIPreset) => {
    // Preset is automatically selected in the hook
    // Could trigger auto-generation here if desired
  }

  useEffect(() => {
    if (canGenerateSummary()) {
      fetchSummary()
    }
  }, [appTimeData, dailyScreenTimeData, canGenerateSummary, fetchSummary])

  return (
    <Card>
      <CardHeader>
        <div className="flex justify-between items-center">
          <div>
            <CardTitle className="font-sans tracking-tighter font-semibold">
              <div>Summary</div>
            </CardTitle>
            <CardDescription>Analysis report generated by AI</CardDescription>
          </div>
          <div className="flex gap-2 items-center">
            <div className="font-mono text-sm font-light flex gap-1 items-center justify-center">
              <p>AI Model:</p>
              <AIPresetSelector 
                className="w-64"
                onPresetSelect={handlePresetSelect}
              />
            </div>
            {canGenerateSummary() && (
              <Button onClick={fetchSummary} disabled={loading} size="sm">
                {loading ? "Generating..." : "Regenerate"}
              </Button>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {!canGenerateSummary() ? (
          <div>
            <p className="text-sm text-gray-600">
              Please select an AI preset to generate a summary.
            </p>
            <p className="text-xs text-gray-500 mt-2">
              Configure AI settings in screenpipe or provide an OpenRouter API key in the settings below.
            </p>
          </div>
        ) : loading ? (
          <p>Loading...</p>
        ) : summary ? (
          <div dangerouslySetInnerHTML={{ __html: summary }} />
        ) : (
          <p>No summary generated yet. Click &quot;Regenerate&quot; to create one.</p>
        )}
      </CardContent>
    </Card>
  )
}

export default Summary
